In [1]:
import csv
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import LinearSVC
from sklearn.multiclass import OneVsRestClassifier, OneVsOneClassifier
import numpy as np
import pandas as pd
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize 
from nltk.stem import SnowballStemmer

In [2]:
train_set = []
test_set = []

In [3]:
with open('train.tsv', 'r') as f:
    sentimentreader = csv.reader(f, delimiter='\t')
    header = next(sentimentreader)
    cnt = 0
    for row in sentimentreader:
        sentence = row[2]
        sentiment = row[3]
        if (cnt < 30):
            test_set.append((sentence, sentiment))
        elif (cnt > 30):
            train_set.append((sentence, sentiment))
        cnt += 1

In [29]:
train_set

[('good for the gander , some of which occasionally amuses but none of which amounts to much of a story',
  '2'),
 ('for the gander , some of which occasionally amuses but none of which amounts to much of a story',
  '2'),
 ('the gander , some of which occasionally amuses but none of which amounts to much of a story',
  '1'),
 ('the gander ,', '2'),
 ('the gander', '2'),
 ('gander', '2'),
 (',', '2'),
 ('some of which occasionally amuses but none of which amounts to much of a story',
  '2'),
 ('some of which', '2'),
 ('some', '2'),
 ('of which', '2'),
 ('which', '2'),
 ('occasionally amuses but none of which amounts to much of a story', '2'),
 ('occasionally', '2'),
 ('amuses but none of which amounts to much of a story', '2'),
 ('amuses', '3'),
 ('but none of which amounts to much of a story', '1'),
 ('but', '2'),
 ('none of which amounts to much of a story', '1'),
 ('none', '2'),
 ('of which amounts to much of a story', '2'),
 ('which amounts to much of a story', '2'),
 ('amounts to 

In [4]:
sentence_set = [sentence for sentence, label in train_set]
label_set = [int(label) for sentence, label in train_set]


In [7]:
from sklearn import model_selection
Xtrain,Xtest,Ytrain,Ytest = model_selection.train_test_split(sentence_set,label_set,test_size=0.3,random_state=1701)

In [2]:
# print(len(Xtrain))
# print(len(Ytrain))
# print(len(Xtest))
# print(len(Ytest))

# Support Vector Classifier

In [19]:
text_clf_svm = Pipeline([('vect', CountVectorizer()),
                     ('tfidf', TfidfTransformer()),
                     ('clf', LinearSVC()),
                     ])
X_train = np.asarray(Xtrain)
text_class_svm = text_clf_svm.fit(X_train, np.asarray(Ytrain))
print(text_class_svm)

Pipeline(steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip...ax_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0))])


In [65]:
pred_train_svm = text_class_svm.predict(np.asarray(Xtrain))
# Test to check whether our classifier makes prediction across all categories
print(np.unique(pred_train_svm))  
pred_test_svm = text_class_svm.predict(np.asarray(Xtest))
# Test to check whether our classifier makes prediction across all categories
print(np.unique(pred_test_svm)) 


[0 1 2 3 4]
[0 1 2 3 4]


In [27]:
from sklearn.metrics import classification_report
target_names = ['negative-0', 'somewhat negative-1', 'neutral-2','somewhat positive-3','positive-4']
print(classification_report(y_pred = pred_train_svm, y_true=np.asarray(Ytrain), target_names=target_names))
print(classification_report(y_pred = pred_test_svm, y_true=np.asarray(Ytest), target_names=target_names))

                     precision    recall  f1-score   support

         negative-0       0.71      0.43      0.54      4905
somewhat negative-1       0.67      0.58      0.62     19012
          neutral-2       0.76      0.89      0.82     55679
somewhat positive-3       0.68      0.61      0.64     23145
         positive-4       0.74      0.45      0.56      6479

        avg / total       0.72      0.73      0.72    109220

                     precision    recall  f1-score   support

         negative-0       0.51      0.29      0.37      2167
somewhat negative-1       0.53      0.44      0.48      8260
          neutral-2       0.70      0.84      0.76     23875
somewhat positive-3       0.56      0.49      0.52      9780
         positive-4       0.55      0.34      0.42      2727

        avg / total       0.62      0.64      0.62     46809



# Stochastic Gredient Descent

In [41]:
# from mlxtend.preprocessing import DenseTransformer
from sklearn.linear_model import SGDClassifier
text_clf_sgd = Pipeline([('vect', CountVectorizer()),
                     ('tfidf', TfidfTransformer()),
                     ('clf', SGDClassifier())
                     ])
X_train = np.asarray(Xtrain)
text_class_sgd = text_clf_sgd.fit(X_train, np.asarray(Ytrain))
# print(text_class_sgd)

Pipeline(steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip...   penalty='l2', power_t=0.5, random_state=None, shuffle=True,
       verbose=0, warm_start=False))])


In [42]:
pred_train_sgd = text_class_sgd.predict(np.asarray(Xtrain))
# Test to check whether our classifier makes prediction across all categories
print(np.unique(pred_train_sgd))  
pred_test_sgd = text_class_sgd.predict(np.asarray(Xtest))
# Test to check whether our classifier makes prediction across all categories
print(np.unique(pred_test_sgd))  


[0 1 2 3 4]
[0 1 2 3 4]


In [43]:
from sklearn.metrics import classification_report
target_names = ['negative-0', 'somewhat negative-1', 'neutral-2','somewhat positive-3','positive-4']
print(classification_report(y_pred = pred_train_sgd, y_true=np.asarray(Ytrain), target_names=target_names))
print(classification_report(y_pred = pred_test_sgd, y_true=np.asarray(Ytest), target_names=target_names))

                     precision    recall  f1-score   support

         negative-0       0.66      0.13      0.22      4905
somewhat negative-1       0.56      0.14      0.23     19012
          neutral-2       0.58      0.95      0.72     55679
somewhat positive-3       0.57      0.26      0.36     23145
         positive-4       0.67      0.16      0.26      6479

        avg / total       0.58      0.58      0.51    109220

                     precision    recall  f1-score   support

         negative-0       0.50      0.10      0.17      2167
somewhat negative-1       0.50      0.12      0.19      8260
          neutral-2       0.58      0.95      0.72     23875
somewhat positive-3       0.52      0.22      0.31      9780
         positive-4       0.57      0.14      0.23      2727

        avg / total       0.55      0.57      0.49     46809



# Multinomial Naive Bayes

In [34]:
from mlxtend.preprocessing import DenseTransformer

In [35]:

from sklearn.naive_bayes import MultinomialNB
text_clf_mnb = Pipeline([('vect', CountVectorizer()),
                     ('tfidf', TfidfTransformer()),
                     ('clf', MultinomialNB())
                     ])
X_train = np.asarray(Xtrain)
text_class_mnb = text_clf_mnb.fit(X_train, np.asarray(Ytrain))
print(text_class_mnb)

Pipeline(steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip...inear_tf=False, use_idf=True)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])


In [36]:
pred_train_mnb = text_class_mnb.predict(np.asarray(Xtrain))
print(np.unique(pred_train_mnb))  # Test to check whether our classifier makes prediction across all categories
pred_test_mnb = text_class_mnb.predict(np.asarray(Xtest))
print(np.unique(pred_test_mnb))  # Test to check whether our classifier makes prediction across all categories



[0 1 2 3 4]
[0 1 2 3 4]


In [56]:
from sklearn.metrics import classification_report
target_names = ['negative-0', 'somewhat negative-1', 'neutral-2','somewhat positive-3','positive-4']
print(classification_report(y_pred = pred_train_mnb, y_true=np.asarray(Ytrain), target_names=target_names))
print(classification_report(y_pred = pred_test_mnb, y_true=np.asarray(Ytest), target_names=target_names))

                     precision    recall  f1-score   support

         negative-0       0.84      0.05      0.09      4905
somewhat negative-1       0.64      0.30      0.41     19012
          neutral-2       0.63      0.94      0.76     55679
somewhat positive-3       0.62      0.44      0.51     23145
         positive-4       0.84      0.07      0.13      6479

        avg / total       0.65      0.63      0.58    109220

                     precision    recall  f1-score   support

         negative-0       0.63      0.03      0.06      2167
somewhat negative-1       0.51      0.24      0.33      8260
          neutral-2       0.60      0.90      0.72     23875
somewhat positive-3       0.53      0.37      0.44      9780
         positive-4       0.65      0.05      0.09      2727

        avg / total       0.58      0.58      0.53     46809



# Grid Search

In [44]:
from sklearn.model_selection import GridSearchCV
parameters = {'vect__ngram_range': [(1, 1), (1, 2)],
              'tfidf__use_idf': (True, False),
              'clf__alpha': (1e-2, 1e-3),
}

In [66]:
gs_clf_mnb = GridSearchCV(text_class_mnb, parameters, n_jobs=-1)

In [68]:
gs_clf_mnb = gs_clf_mnb.fit(Xtrain, Ytrain)

In [69]:
print(gs_clf_mnb.best_score_ )

0.585716901666


In [52]:
for param_name in sorted(parameters.keys()):
    print("%s: %r" % (param_name, gs_clf_mnb.best_params_[param_name]))

clf__alpha: 0.01
tfidf__use_idf: True
vect__ngram_range: (1, 1)
